<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fa fa-bars"></i> </button>
            <a class="navbar-brand page-scroll" href="#page-top"> <i class="fa fa-play-circle"></i> <span class="light">Start</span> Clone Twitter </a> </div>
    </div>
    <!-- /.container -->
</nav>
<!-- Intro Header -->
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1>Welcome to Clone Twitter.</h1>
                    <p class="intro-text">Connect with your friends — and other fascinating people. Get in-the-moment updates on the things that interest you. And watch events unfold, in real time, from every angle.</p>
                </div>
                <div class="col-md-4 col-md-offset-1 right-home">
                    <div class="form">
                        <form method="post" action="<?php echo $this->url(array('controller' => 'Auth', 'action' => 'login')); ?>" role="form" class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" id="signin-email" name="username_signin" autocomplete="on" class="form-control" placeholder="Phone, email, username">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-9">
                                    <input type="password" id="signin-password" name="password_signin" placeholder="Password" class="form-control">
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        Login
                                    </button>
                                </div>
                            </div>
                            <div class="form-links">
                                <label>
                                    <input type="checkbox" value="1" name="remember_me">
                                    Remember me</label>
                                - <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'forgot')); ?>">For got password</a> </div>
                        </form>
                    </div>
                    <div class="form">
                        <form method="post" action="<?php echo $this->url(array('controller' => 'User', 'action' => 'signup')); ?>" role="form">
                            <div class="form-group"> Next to Twitter? Sign up</div>
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder="Full name..." >
                            </div>
                            <div class="form-group">
                                <input type="text" id="email" name="email" class="form-control" placeholder="Email...">
                            </div>
                            <div class="form-group">
                                <input type="password" id="password" name="password" placeholder="Password" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" id="phonenumber" name="phonenumber" placeholder="Phone number" class="form-control">
                            </div>
                            <div class="clearfix">
                                <button class="btn pull-right btn-warning" type="submit">Sign me up!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>