<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fa fa-bars"></i> </button>
            <a class="navbar-brand page-scroll" href="/#page-top"> <i class="fa fa-play-circle"></i> <span class="light">Start</span> Clone Twitter </a> </div>
    </div>
    <!-- /.container -->
</nav>
<!-- Intro Header -->
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1>Welcome to Clone Twitter.</h1>
                    <p class="intro-text">Connect with your friends — and other fascinating people. Get in-the-moment updates on the things that interest you. And watch events unfold, in real time, from every angle.</p>
                </div>
                <div class="col-md-4 col-md-offset-1 right-home">
                    <div class="form">
                        <form method="post" action="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login')); ?>" role="form" class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" id="signin-email"
                                        name="username" autocomplete="on"
                                        class="form-control"
                                        placeholder="Phone, email, username"
                                        required autofocus />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-9">
                                    <input type="password" id="signin-password"
                                        name="password" placeholder="Password"
                                        class="form-control"
                                        required autofocus />
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        Login
                                    </button>
                                </div>
                            </div>
                            <div class="form-links">
                                <label>
                                    <input type="hidden" value="0" name="remember_me" />
                                    <input type="checkbox" value="1" name="remember_me" />
                                    Remember me</label>
                                - <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'forgot')); ?>">For got password</a> </div>
                        </form>
                    </div>
                    <?php echo $this->render('user/register.form.phtml');?>
                </div>
            </div>
        </div>
    </div>
</header>
