<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Twitter clone');
$this->headLink()->headLink(array(
    'rel' => 'shortcut icon',
    'href' => $this->baseUrl('favicon.ico'),
    'type' => 'image/x-icon'
));
$this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap.min.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/grayscale.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/font-awesome/css/font-awesome.min.css'));
$this->headLink()->appendStylesheet("http://fonts.googleapis.com/css?family=Montserrat:400,700");

$this->headScript()->appendFile($this->baseUrl("/js/jquery.js"));
$this->headScript()->appendFile($this->baseUrl("/js/bootstrap.min.js"));
$this->headScript()->appendFile($this->baseUrl("/js/jquery.easing.min.js"));
$this->headScript()->appendFile($this->baseUrl("/js/grayscale.js"));


echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php
        echo $this->headMeta(), PHP_EOL;
        echo $this->headTitle(), PHP_EOL;
        echo $this->headLink(), PHP_EOL;
    ?>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<?php //echo $this->render('_menu.phtml'); ?>

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fa fa-bars"></i> </button>
                <a class="navbar-brand page-scroll" href="#page-top"> <i class="fa fa-play-circle"></i> <span class="light">Start</span> Clone Twitter </a> </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                        <li class="hidden"> <a href="#page-top"></a> </li>
                        <li> <a class="page-scroll" href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>">logout</a> </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- About Section -->
    <section class="container content-section">
        <div class="row">
            <div class="col-md-3 panel panel-default">
                <div class="sidebar">
                    <?php echo $this->profileInfo();?>
                </div>
                <div class="sidebar">
                    <div class="flex-module-inner">
                        <ul class="list-unstyled">
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'dashboard')); ?>">Dashboard</a> </li>
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'addtweet')); ?>">Add Tweet</a> </li>
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'viewall')); ?>">View all user you don't follow</a> </li>
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'viewallfollowing')); ?>">View all user you follow</a> </li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php echo $this->layout()->content; ?>
            <div class="col-md-3  panel panel-default">
                <div class="sidebar">
                    <ul class="list-inline list-inline list-unstyled">
                        <li class="Footer-item Footer-copyright copyright">&copy; 2015 Twitter</li>
                        <li class="Footer-item"><a href="#" class="Footer-link">About</a></li>
                        <li class="Footer-item"><a href="#" class="Footer-link">Help</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </footer>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl('/js/html5shiv.js');?>"></script>
    <script src="<?php echo $this->baseUrl('/js/respond.min.js') ?>"></script>
    <![endif]-->
    <?php
        echo $this->headScript(), PHP_EOL;
        echo $this->inlineScript(), PHP_EOL;
    ?>
</body>
</html>
