<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Twitter clone');
$this->headLink()->headLink(array(
    'rel' => 'shortcut icon',
    'href' => $this->baseUrl('favicon.ico'),
    'type' => 'image/x-icon'
));
$this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap.min.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/grayscale.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/font-awesome/css/font-awesome.min.css'));
$this->headLink()->appendStylesheet("http://fonts.googleapis.com/css?family=Montserrat:400,700");

$this->headScript()->appendFile($this->baseUrl("/js/jquery.js"));
$this->headScript()->appendFile($this->baseUrl("/js/bootstrap.min.js"));
$this->headScript()->appendFile($this->baseUrl("/js/jquery.easing.min.js"));
$this->headScript()->appendFile($this->baseUrl("/js/grayscale.js"));
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php
        echo $this->headMeta(), PHP_EOL;
        echo $this->headTitle(), PHP_EOL;
        echo $this->headLink(), PHP_EOL;?>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<?php //echo $this->render('_menu.phtml'); ?>
    <?php echo $this->layout()->content; ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl('/js/html5shiv.js');?>"></script>
    <script src="<?php echo $this->baseUrl('/js/respond.min.js') ?>"></script>
    <![endif]-->
    <?php
        echo $this->headScript(), PHP_EOL;
        echo $this->inlineScript(), PHP_EOL;
    ?>
</body>
</html>
