<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Twitter clone');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <!-- Bootstrap Core CSS -->
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/bootstrap.min.css'));?>
    <!-- Custom CSS -->
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/grayscale.css'));?>
    <!-- Custom Fonts -->
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/font-awesome/css/font-awesome.min.css'));?>
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<?php //echo $this->render('_menu.phtml'); ?>

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fa fa-bars"></i> </button>
                <a class="navbar-brand page-scroll" href="#page-top"> <i class="fa fa-play-circle"></i> <span class="light">Start</span> Clone Twitter </a> </div>
        </div>
        <!-- /.container -->
    </nav>

    <!-- About Section -->
    <section class="container content-section">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar">
                    <?php echo $this->profileInfo();?>
                </div>
                <div class="sidebar">
                    <div class="flex-module-inner">
                        <ul class="list-unstyled">
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'dashboard')); ?>">Dashboard</a> </li>
                            <li> <a href="#">Add Tweet</a> </li>
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'viewall')); ?>">View all user you don't follow</a> </li>
                            <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'viewallfollowing')); ?>">View all user you follow</a> </li>
                        </ul>
                    </div>
                </div>
            </div>
    <?php echo $this->layout()->content; ?>
            <div class="col-md-3">
                <div class="sidebar">
                    <ul class="list-inline list-inline list-unstyled">
                        <li class="Footer-item Footer-copyright copyright">&copy; 2015 Twitter</li>
                        <li class="Footer-item"><a href="#" class="Footer-link">About</a></li>
                        <li class="Footer-item"><a href="#" class="Footer-link">Help</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </footer>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <?php echo $this->headScript()->prependFile($this->baseUrl("/js/html5shiv.js"));?>
    <?php echo $this->headScript()->prependFile($this->baseUrl("/js/respond.min.js"));?>
    <![endif]-->
    <!-- jQuery -->
    <?php echo $this->headScript()->prependFile($this->baseUrl("/js/jquery.js"));?>
    <!-- Bootstrap Core JavaScript -->
    <?php echo $this->headScript()->prependFile($this->baseUrl("/js/bootstrap.min.js"));?>
    <!-- Plugin JavaScript -->
    <?php echo $this->headScript()->prependFile($this->baseUrl("/js/jquery.easing.min.js"));?>
    <!-- Custom Theme JavaScript -->
    <?php echo $this->headScript()->prependFile($this->baseUrl("/js/grayscale.js"));?>
</body>
</html>