<?php
$form = $this->formRegister;
$form->setAction($this->url(array('controller' => 'user', 'action' => 'signup')));

$nameError = $form->name->getMessages();
$hasNameError = !empty($nameError);

$emailError = $form->email->getMessages();
$hasEmailError = !empty($emailError);

$passError = $form->password->getMessages();
$hasPassError = !empty($passError);

$phoneError = $form->phonenumber->getMessages();
$hasPhoneError = !empty($phoneError);
?>
<div class="form">
    <form method="post" action="<?php echo $form->getAction(); ?>" role="form">
        <div class="form-group"> Next to Twitter? Sign up</div>
        <div class="form-group <?php if($hasNameError):?>has-error<?php endif;?>">
            <input type="text" id="name" name="name"
                value="<?php echo $form->name->getValue();?>"
                class="form-control" placeholder="Full name..."
                required
                 focus />
                <?php
                if ($hasNameError):
                    foreach($nameError as $errMessage):
                ?>
                    <span class="help-block with-errors"><?php echo $errMessage; ?></span>
                <?php
                    endforeach;
                endif;
                ?>
        </div>
        <div class="form-group <?php if($hasEmailError):?>has-error<?php endif;?>">
            <input type="text" id="email" name="email"
                value="<?php echo $form->email->getValue();?>"
                class="form-control" placeholder="Email..."
                required
                 />
             <?php
                if ($hasEmailError):
                    foreach($emailError as $errMessage):
                ?>
                    <span class="help-block with-errors"><?php echo $errMessage; ?></span>
                <?php
                    endforeach;
                endif;
                ?>
        </div>
        <div class="form-group  <?php if($hasPassError):?>has-error<?php endif;?>">
            <input type="password" id="password" name="password"
                value="<?php echo $form->password->getValue();?>"
                placeholder="Password" class="form-control"
                required
                 />
                <?php
                if ($hasPassError):
                    foreach($passError as $errMessage):
                ?>
                    <span class="help-block with-errors"><?php echo $errMessage; ?></span>
                <?php
                    endforeach;
                endif;
                ?>
        </div>
        <div class="form-group  <?php if($hasPhoneError):?>has-error<?php endif;?>">
            <input type="text" id="phonenumber" name="phonenumber"
                value="<?php echo $form->phonenumber->getValue();?>"
                placeholder="Phone number" class="form-control" required />
            <?php
                if ($hasPhoneError):
                    foreach($phoneError as $errMessage):
                ?>
                    <span class="help-block with-errors"><?php echo $errMessage; ?></span>
                <?php
                    endforeach;
                endif;
                ?>
        </div>
        <div class="clearfix">
            <button class="btn pull-right btn-warning" type="submit">Sign me up!</button>
        </div>
    </form>
</div>
