<nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"> <i class="fa fa-bars"></i> </button>
            <a class="navbar-brand page-scroll" href="/#page-top"> <i class="fa fa-play-circle"></i> <span class="light">Start</span> Clone Twitter </a> </div>
    </div>
</nav>
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 right-home">
                    <?php echo $this->render('user/register.form.phtml');?>
                </div>
            </div>
        </div>
    </div>
</header>
