<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-body">
            <h5> Here are all people you followed. </h5>
         </div>
        <div class="panel-footer">
            <div class="row">
                <?php if (count($this->allFollowingUser)==0):?>
                    <p>You don't follow any user</p>
                <?php else:?>
                    <?php foreach ($this->allFollowingUser as $user):?>
                        <div class="col-md-4">
                            <a class="account-group js-account-group js-user-profile-link">
                                <img width="128" height="128" data-user-id="2775565190" class="avatar size128 js-action-profile-avatar" alt="2idea" src="<?php echo $this->baseUrl('../../img/mdjaJZiZ_reasonably_small.png')?>">
                            <span class="account-group-inner js-action-profile-name">
                                <strong class="fullname"><?php echo $user->getFullname();?></strong>
                                <small data-user-id="2775565190" class="username"><?php echo $user->getUsername();?></small>
                            </span>
                            </a>
                            <a class="btn btn-default" href="<?php echo $this->url(array('controller' => 'follow', 'action' => 'unfollowing'));?>/id/<?php echo $user->getId()?>"> <span class="glyphicon glyphicon-user"></span> Unfollow</a>
                        </div>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
